### ISSUE TITLE
puppet_service_name for debian based systems

### ISSUE THREAD

**Issue by toepi** [abstractitptyltd/abstractit-puppet#54]
`puppet_service_name` of `::puppetdb::master::config` is set to `puppetserver` in case of use new puppetserver and to `httpd` when use passenger. But httpd is the service name on RedHat, on Debian is called apache2. Add `osfamilly` to logic for `puppet_service_name` or move it to `puppet::defaults`?

**Comment by rendhalver** [comment]
I use the puppetlabs-apache module to manage passenger and it uses httpd as the name of the service for both Debian and RedHat systems.
The setting you mentioned is now in puppet::profile::master and only gets used to setup PuppetDB.

So if you use my module or puppetlabs-apache to setup passenger then it will work as expected.

**Comment by toepi** [comment]
I use `puppetlabs-apache`module to install and configure passenger too. But take a look at `https://github.com/puppetlabs/puppetlabs-apache/blob/master/manifests/params.pp` they use different service names? But If you say the current service name `httpd` work for you on debian too - it is okay than we can close this issue? Have only found it after look at your code.

**Comment by rendhalver** [comment]
They do use a different service name for each platform but the name of the resource that manages the service is still called httpd for all platforms.
It's a little confusing but the name of the resource is more important because that is what the PuppetDB classes will notify.
Have a look here.
https://github.com/puppetlabs/puppetlabs-apache/blob/master/manifests/service.pp#L42

**Comment by toepi** [comment]
Oh sorry, has not see this. My mapping is service name => init-script name, but define aother name is a nice(r) solution.
